[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Deploy preview context
[context.deploy-preview]
  environment = { NODE_ENV = "production" }

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_ENV = "production" }

# Asset optimization
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true